credential:
    service:
        emailing:
            username: OPRAYfIcIangtOpRothEdThIvEnADjOhaPItEcKHANGOnISHAREHElaSKIwiNtANDoGRiSCAtoRdleyebAsyMCapHOcKPaNiCurI_id-menara-holding-service-emailing
            password: uCleSIoNYoUtlENgEStICiverbOArDeWLargETiONCKINosaVOTarKmACoPINDaTERMANtErnFercHtiOunwaSaGibLeuRETranKAtecHRimatElABlenteRIOmETerNeANtRacloUtOnISterFiceoUstoUsKenTZENAtENaLYsTRAChANTLaMUltviCKEymesIOnZy