credential:
    service:
        user:
            username: IrCOCoaONojeEiCGSerAacjtDEtGAKRSPEoDgeavHOCaECdithIRatcRRKDidIMRAvjHRSwitEHAOsReaOROlIKpStiPIAaACMot_id-menara-holding-service-user
            password: LUOAnvlneYrrCrStPoNKyERNErirliLEelNZasmnIIoNnKeHluAHoUtTENtwUOICRmEnCPAleAYTNetICILEeEaEtUtDKNEAeUAeyEEntersmAgtgVMrnCInsTIIrmKaretbOstlneeUsVtauNFnNTKNRONEURRMCiCDtSoyDneIteTtKNwONrOttEotaAanUUNnErUr