export GIT_URI="https://github.com/Yassine-Chalati/Habit-App.git"
export USERNAME_GIT="Yassine-Chalati"
export PASSWORD_GIT="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"
export GIT_SEARCH_PATH_PREFIX="ConfigurationRepository"
export TRY_MASTER_BRANCH="false"