export GIT_URI="https://github.com/Yassine-Chalati/InternshipHiringMenaraBack.git"
export USERNAME_GIT="Yassine-Chalati"
export PASSWORD_GIT="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"
export GIT_SEARCH_PATH_PREFIX="4_Increments/ConfigurationRepository"
export TRY_MASTER_BRANCH="false"