server:
  port: 8001

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yassine.chalati.07@gmail.com
    password: mnyx bhkw hqsg cuou
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true