global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'registry-service'
    scrape_interval: 15s
    static_configs:
      - targets: ['77.37.86.136:8000']

  - job_name: 'config-service'
    scrape_interval: 15s
    static_configs:
      - targets: ['77.37.86.136:8001']

  - job_name: 'gateway-service'
    scrape_interval: 15s
    static_configs:
      - targets: ['77.37.86.136:8002']

  - job_name: 'emailing-service'
    scrape_interval: 15s
    static_configs:
      - targets: ['77.37.86.136:8013']

  - job_name: 'profile-service'
    scrape_interval: 15s
    static_configs:
      - targets: ['77.37.86.136:8012']

  - job_name: 'authentication-service'
    scrape_interval: 15s
    static_configs:
      - targets: ['77.37.86.136:8011']