package com.habitapp.authentication_service.domain.facade;

import com.habitapp.authentication_service.domain.exception.account.*;
import com.habitapp.authentication_service.domain.exception.account.RoleNotDefinedException;
import com.habitapp.authentication_service.domain.exception.account.RoleNotFoundException;
import com.habitapp.authentication_service.domain.exception.account.RolePrefixException;
import com.habitapp.authentication_service.domain.exception.authentication.AuthenticationTypeNullPointerException;
import com.habitapp.authentication_service.domain.exception.authentication.UnknownAuthenticationTypeException;
import com.habitapp.authentication_service.domain.exception.general.ValueNullException;
import com.habitapp.authentication_service.dto.account.*;
import com.habitapp.authentication_service.dto.jwt.AccessTokenAndRefreshTokenAndFingerPrintDTO;
import com.habitapp.authentication_service.dto.jwt.JsonWebTokenConnectionInformationDTO;

import java.util.List;

public interface AccountFacade {
    public AccountIdAndEmailAndActivationURLDTO createIndividualAccountWithDefaultMethod(AccountAndRolesAndPermissionsDTO account) throws PasswordNotFoundException, EmailNotFoundException, EmailPatternNotValidException, AccountAlreadyExistsException, RolePrefixException, RoleNotDefinedException, PermissionPrefixException, AccountNotCreatedException, PermissionNotDefinedException, RoleNotFoundException, UrlConfigurationNotFoundException, PasswordPatternNotValidException;
    AccessTokenAndRefreshTokenAndFingerPrintDTO activateTheIndividualAccountCreatedByDefaultMethod(AccountEmailAndActivationTokenDTO accountEmailAndActivationTokenDTO, JsonWebTokenConnectionInformationDTO jsonWebTokenConnectionInformation) throws EmailNotFoundException, EmailPatternNotValidException, VerificationTokenNotFoundException, VerificationTokenPatternNotValidException, VerificationTokenDurationExpiredException, VerificationTokensNotEqualsException, AccountNotFoundException, AccountIsActivatedException, ValueNullException, AuthenticationTypeNullPointerException, UnknownAuthenticationTypeException;
    public AccountEmailAndUrlDTO generateActivationUrlForAccountCreatedByDefaultMethod(String email) throws EmailNotFoundException, EmailPatternNotValidException, VerificationTokenException, UrlConfigurationNotFoundException, AccountNotFoundException, VerificationTokenNotRegeneratedYetException;
}
