package com.menara.authentication.domain.facade;

import com.menara.authentication.domain.exception.account.*;
import com.menara.authentication.domain.exception.account.RoleNotDefinedException;
import com.menara.authentication.domain.exception.account.RoleNotFoundException;
import com.menara.authentication.domain.exception.account.RolePrefixException;
import com.menara.authentication.domain.exception.authentication.AuthenticationTypeNullPointerException;
import com.menara.authentication.domain.exception.authentication.UnknownAuthenticationTypeException;
import com.menara.authentication.domain.exception.general.ValueNullException;
import com.menara.authentication.dto.account.*;
import com.menara.authentication.dto.jwt.AccessTokenAndRefreshTokenAndFingerPrintDTO;
import com.menara.authentication.dto.jwt.JsonWebTokenConnectionInformationDTO;

import java.util.List;

public interface AccountFacade {
    public AccountIdAndEmailAndActivationURLDTO createCandidateAccountWithDefaultMethod(AccountAndRolesAndPermissionsDTO account) throws PasswordNotFoundException, EmailNotFoundException, EmailPatternNotValidException, AccountAlreadyExistsException, RolePrefixException, RoleNotDefinedException, PermissionPrefixException, AccountNotCreatedException, PermissionNotDefinedException, RoleNotFoundException, UrlConfigurationNotFoundException, PasswordPatternNotValidException;
    public long createAdminAccount(AccountAndRolesAndPermissionsDTO account) throws EmailNotFoundException, PasswordNotFoundException, EmailPatternNotValidException, PasswordPatternNotValidException, AccountAlreadyExistsException, RoleNotFoundException, RolePrefixException, RoleNotDefinedException, PermissionPrefixException, PermissionNotDefinedException, AccountNotCreatedException;
    public void updateAdminAccountSuspensionState(long idAccount, Boolean value) throws AccountNotFoundException, ValueNullException, AuthenticationTypeNullPointerException, UnknownAuthenticationTypeException;
    public void updateAdminAccountPassword(long idAccount, String newPassword) throws AccountNotFoundException, PasswordNotFoundException, PasswordPatternNotValidException, ValueNullException, AuthenticationTypeNullPointerException, UnknownAuthenticationTypeException;
    public void deleteOneAdminAccount(long idAccount) throws AccountNotFoundException;
    AccessTokenAndRefreshTokenAndFingerPrintDTO activateTheCandidateAccountCreatedByDefaultMethod(AccountEmailAndActivationTokenDTO accountEmailAndActivationTokenDTO, JsonWebTokenConnectionInformationDTO jsonWebTokenConnectionInformation) throws EmailNotFoundException, EmailPatternNotValidException, VerificationTokenNotFoundException, VerificationTokenPatternNotValidException, VerificationTokenDurationExpiredException, VerificationTokensNotEqualsException, AccountNotFoundException, AccountIsActivatedException, ValueNullException, AuthenticationTypeNullPointerException, UnknownAuthenticationTypeException;
    public AccountEmailAndUrlDTO generateActivationUrlForAccountCreatedByDefaultMethod(String email) throws EmailNotFoundException, EmailPatternNotValidException, VerificationTokenException, UrlConfigurationNotFoundException, AccountNotFoundException, VerificationTokenNotRegeneratedYetException;
    public long createCandidateAccountWithGoogleMethod(AccountEmailAndRolesAndPermissionsDTO account) throws EmailNotFoundException, EmailPatternNotValidException, AccountAlreadyExistsException, RolePrefixException, RoleNotDefinedException, PermissionPrefixException, AccountNotCreatedException, PermissionNotDefinedException, RoleNotFoundException;
    public AccountEmailAndUrlDTO generateResetPasswordUrlForAccountCreatedByDefaultMethod(String email) throws UrlConfigurationNotFoundException, EmailNotFoundException, EmailPatternNotValidException, AccountNotFoundException, VerificationTokenNotRegeneratedYetException;
    public void resetPasswordTheCandidateAccountCreatedByDefaultMethod(AccountEmailAndNewPasswordAndActivationTokenDTO accountEmailAndNewPasswordAndActivationTokenDTO) throws PasswordNotFoundException, EmailNotFoundException, EmailPatternNotValidException, VerificationTokensNotEqualsException, VerificationTokenPatternNotValidException, AccountNotFoundException, VerificationTokenDurationExpiredException, PasswordPatternNotValidException, VerificationTokenNotFoundException;

    List<String> readAllAdminRoles();

    List<String> readAllAdminPermissions();
}
