spring:
  application:
    name: habit-service
  profiles:
    active: ${PROFILES},
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-service
      fail-fast: true
      retry:
        max-attempts: 10
      label: ${GIT_BRANCH}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 7
  client:
    refresh:
      enable: false
    service-url:
      defaultZone: ${HTTP}://${BASIC_AUTH_EUREKA}${DNS}/eureka/



  datasource:
    url: jdbc:mysql://localhost:3306/base
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect